---
name: runtimepy
version: "{{major}}.{{minor}}.{{patch}}"
description: A framework for implementing Python services.
entry: {{entry}}

requirements:
  - vcorelib>=2.8.3
  - websockets
  - "windows-curses; sys_platform == 'win32'"

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper
  - types-setuptools
  - "uvloop; sys_platform != 'win32' and sys_platform != 'cygwin'"

commands:
  - name: arbiter
    description: "run a connection-arbiter application from a config"
  - name: tui
    description: "run a terminal interface for the channel environment"

init_local: |
  METRICS_NAME = "metrics"
