---
name: runtimepy
version: "{{major}}.{{minor}}.{{patch}}"
description: A framework for implementing Python services.
entry: {{entry}}
requirements: []
dev_requirements:
  - setuptools-wrapper
  - vcorelib
  - types-setuptools
