---
name: runtimepy
version: "{{major}}.{{minor}}.{{patch}}"
description: A framework for implementing Python services.
entry: {{entry}}

requirements:
  - vcorelib
  - "windows-curses; sys_platform == 'win32'"

dev_requirements:
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: tui
    description: "run a terminal interface for the channel environment"
