---
name: runtimepy
version: "{{major}}.{{minor}}.{{patch}}"
description: A framework for implementing Python services.
entry: {{entry}}

requirements:
  - vcorelib>=3.2.0
  - svgen>=0.6.4
  - websockets
  - "windows-curses; sys_platform == 'win32' and python_version < '3.12'"

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper
  - types-setuptools
  - "uvloop; sys_platform != 'win32' and sys_platform != 'cygwin'"

commands:
  - name: arbiter
    description: "run a connection-arbiter application from a config"
  - name: server
    description: "run a server for a specific connection factory"
  - name: task
    description: "run a task from a specific task factory"
  - name: tui
    description: "run a terminal interface for the channel environment"

init_local: |
  METRICS_NAME = "metrics"
