---
name: runtimepy
version: "{{major}}.{{minor}}.{{patch}}"
description: A framework for implementing Python services.
entry: {{entry}}

requirements:
  - vcorelib>=2.0.2
  - websockets
  - "windows-curses; sys_platform == 'win32'"

dev_requirements:
  - pytest-asyncio
  - setuptools-wrapper
  - types-setuptools

commands:
  - name: arbiter
    description: "run a connection-arbiter application from a config"
  - name: tui
    description: "run a terminal interface for the channel environment"
