---
includes:
  - package://runtimepy/server.yaml
  - dev_no_wait.yaml
  - ../tests/data/valid/connection_arbiter/test_ssl.yaml

port_overrides:
  runtimepy_https_server: 8443

# This works.
# websocket_hostname: nuc2

app:
  - runtimepy.net.apps.wait_for_stop
