---
includes:
  - package://runtimepy/server.yaml
  - dev_no_wait.yaml
  - ../tests/data/valid/connection_arbiter/test_ssl.yaml

port_overrides:
  runtimepy_https_server: 8443

# This works.
# websocket_hostname: nuc2

config:
  http_redirects:
    secret.html: http://vaughnkottler.com
    secret2.html: https://libre-embedded.com

  top_markdown: |
    # Libre Embedded

    ![logo](/static/svg/chip-circle-bootstrap.svg)

  bottom_markdown: |
    `libre-embedded.com`

app:
  - runtimepy.net.apps.wait_for_stop
