---
includes:
  - package://runtimepy/server.yaml
  - dev_no_wait.yaml
  - ../tests/data/valid/connection_arbiter/test_ssl.yaml

factories:
  - {name: tasks.tlm.LogCapture}
tasks:
  - name: root_log
    factory: log_capture
    period_s: 0.1
    markdown: |
      *something isn't looking right...*

      **why's it looking like that...**

      ***why's it looking like THAT...***

      `nice mono stuff there`

      *`nice slanted mono yeah`*

      **`nice mono bold type shit there`**

      ***`nice mono bold type slant shit there`***

      ligature type shit \_\_\_|\_\_\_ ligature type shit

port_overrides:
  runtimepy_https_server: 8443

# This works.
# websocket_hostname: nuc2

config:
  http_redirects:
    secret.html: http://vaughnkottler.com
    secret2.html: https://libre-embedded.com

  top_markdown: |
    # Libre Embedded

    ![logo](/static/svg/chip-circle-bootstrap.svg)

  bottom_markdown: |
    `libre-embedded.com`

app:
  - runtimepy.net.apps.wait_for_stop
