---
includes_left:
  - package://runtimepy/server.yaml

port_overrides:
  runtimepy_http_server: 8000

clients:
  - factory: tftp
    name: tftp
    kwargs:
      local_addr: [localhost, 8001]

config:
  caching: false

app:
  - runtimepy.net.apps.wait_for_stop
