---
factories:
  - {name: tasks.tlm.SampleTelemetry}
  - {name: tasks.tlm.SampleTelemetryStruct}
  - {name: tasks.tlm.SampleTelemetryPeriodic}

structs:
  - name: tx
    factory: SampleTelemetryStruct
  - name: rx
    factory: SampleTelemetryStruct

tasks:
  - {name: tlm_periodic, factory: sample_telemetry_periodic, period_s: 0.01}

ports:
  - {name: udp_sample_telemetry, type: udp}

clients:
  - factory: SampleTelemetry
    name: rx_conn
    kwargs:
      local_addr: ["0.0.0.0", "$udp_sample_telemetry"]

  - factory: SampleTelemetry
    name: tx_conn
    defer: true
    kwargs:
      remote_addr: ["127.0.0.1", "$udp_sample_telemetry"]

app:
  - tasks.tlm.sample_app
